services:
  - type: web
    name: taff-app
    env: php
    buildCommand: "./build.sh"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: taff-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: taff-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: taff-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: taff-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: taff-db
          property: password

databases:
  - name: taff-db
    ipAllowList: []